
FILE_FORMAT_MULTI_PAGE_TIF = 0
FILE_FORMAT_SINGLE_PAGE_TIF = 1
FILE_FORMAT_PDF = 2

INDEX_SCHEMA_YEAR_DOCUMENT = 3
INDEX_SCHEMA_YEAR_BOOK_PAGE = 4
INDEX_SCHEMA_YEAR_DOCUMENT_BOOK_PAGE = 5

LOCATION_FILE_NAME = 6
LOCATION_DOCUMENT = 7
LOCATION_DOCUMENT_CROPPING = 8
LOCATION_DOCUMENT_HARDCODED = 9
LOCATION_DOCUMENT_SMART_CROPPING = 10

COLLECTION_REGEX = 11